INSERT INTO chartevents
  (ROW_ID, SUBJECT_ID, HADM_ID, ICUSTAY_ID, ITEMID,
   CHARTTIME, STORETIME, CGID, VALUE, VALUENUM,
   VALUEUOM, WARNING, ERROR, RESULTSTATUS, STOPPED)
SELECT
  ROW_ID::INT,
  SUBJECT_ID::INT,
  HADM_ID::INT,
  ICUSTAY_ID::INT,
  ITEMID::INT,

  to_timestamp(CHARTTIME, 'YYYY-MM-DD HH24:MI:SS'),
  to_timestamp(STORETIME, 'YYYY-MM-DD HH24:MI:SS'),

  CGID::INT,

  -- guard for VALUE
  CASE 
    WHEN VALUE   ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN VALUE   ::DOUBLE PRECISION
    ELSE NULL
  END AS VALUE,

  -- guard for VALUENUM
  CASE 
    WHEN VALUENUM~ '^[-+]?[0-9]*\.?[0-9]+$' THEN VALUENUM::DOUBLE PRECISION
    ELSE NULL
  END AS VALUENUM,

  VALUEUOM,
  WARNING::INT,
  ERROR::INT,

  -- guard for RESULTSTATUS
  CASE 
    WHEN RESULTSTATUS ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN RESULTSTATUS::DOUBLE PRECISION
    ELSE NULL
  END AS RESULTSTATUS,

  -- guard for STOPPED
  CASE 
    WHEN STOPPED ~ '^[-+]?[0-9]*\.?[0-9]+$' THEN STOPPED::DOUBLE PRECISION
    ELSE NULL
  END AS STOPPED

FROM chartevents_staging;

DROP TABLE chartevents_staging;
