-- Aggregate features over first 12 hours

DROP TABLE IF EXISTS mp_data_12hr CASCADE;
CREATE TABLE mp_data_12hr AS
SELECT
  d.subject_id,
  d.hadm_id,
  d.icustay_id,
  MAX(dbsource)                     AS dbsource,
  -- ground truth
  MAX(expire_flag)                  AS expire_flag,
  MAX(hospital_expire_flag)         AS hospital_expire_flag,
  MAX(deathtime_hours)              AS deathtime_hours,
  MAX(hosp_deathtime_hours)         AS hosp_deathtime_hours,
  -- demographics / static
  MAX(age)                          AS age,
  MAX(gender)                       AS gender,
  MAX(ethnicity)                    AS ethnicity,
  MAX(admission_type)               AS admission_type,
  MAX(icustay_num)                  AS icustay_num,
  -- vitals & basic labs: means
  AVG(heartrate)                    AS heartrate_mean,
  AVG(sysbp)                        AS sysbp_mean,
  AVG(diasbp)                       AS diasbp_mean,
  AVG(meanbp)                       AS meanbp_mean,
  AVG(resprate)                     AS resprate_mean,
  AVG(tempc)                        AS tempc_mean,
  AVG(spo2)                         AS spo2_mean,
  AVG(glucose)                      AS glucose_mean,
  -- vitals & basic labs: mins
  MIN(heartrate)                    AS heartrate_min,
  MIN(sysbp)                        AS sysbp_min,
  MIN(diasbp)                       AS diasbp_min,
  MIN(meanbp)                       AS meanbp_min,
  MIN(resprate)                     AS resprate_min,
  MIN(tempc)                        AS tempc_min,
  MIN(spo2)                         AS spo2_min,
  MIN(glucose)                      AS glucose_min,
  -- vitals & basic labs: maxs
  MAX(heartrate)                    AS heartrate_max,
  MAX(sysbp)                        AS sysbp_max,
  MAX(diasbp)                       AS diasbp_max,
  MAX(meanbp)                       AS meanbp_max,
  MAX(resprate)                     AS resprate_max,
  MAX(tempc)                        AS tempc_max,
  MAX(spo2)                         AS spo2_max,
  MAX(glucose)                      AS glucose_max,
  -- GCS: mean/min/max
  AVG(gcs)                          AS gcs_mean,
  AVG(gcsmotor)                     AS gcsmotor_mean,
  AVG(gcsverbal)                    AS gcsverbal_mean,
  AVG(gcseyes)                      AS gcseyes_mean,
  AVG(endotrachflag)                AS endotrachflag_mean,
  MIN(gcs)                          AS gcs_min,
  MIN(gcsmotor)                     AS gcsmotor_min,
  MIN(gcsverbal)                    AS gcsverbal_min,
  MIN(gcseyes)                      AS gcseyes_min,
  MIN(endotrachflag)                AS endotrachflag_min,
  MAX(gcs)                          AS gcs_max,
  MAX(gcsmotor)                     AS gcsmotor_max,
  MAX(gcsverbal)                    AS gcsverbal_max,
  MAX(gcseyes)                      AS gcseyes_max,
  MAX(endotrachflag)                AS endotrachflag_max,
  -- Blood gases & advanced labs: mean/min/max
  AVG(bg_baseexcess)                AS baseexcess_mean,
  AVG(bg_carboxyhemoglobin)         AS carboxyhemoglobin_mean,
  AVG(bg_methemoglobin)             AS methemoglobin_mean,
  AVG(bg_po2)                       AS po2_mean,
  AVG(bg_pco2)                      AS pco2_mean,
  AVG(bg_ph)                        AS ph_mean,
  AVG(bg_pao2fio2ratio)             AS pao2fio2ratio_mean,
  AVG(bg_totalco2)                  AS totalco2_mean,
  AVG(aniongap)                     AS aniongap_mean,
  AVG(albumin)                      AS albumin_mean,
  AVG(bands)                        AS bands_mean,
  AVG(bicarbonate)                  AS bicarbonate_mean,
  AVG(bilirubin)                    AS bilirubin_mean,
  AVG(calcium)                      AS calcium_mean,
  AVG(creatinine)                   AS creatinine_mean,
  AVG(chloride)                     AS chloride_mean,
  AVG(hematocrit)                   AS hematocrit_mean,
  AVG(hemoglobin)                   AS hemoglobin_mean,
  AVG(lactate)                      AS lactate_mean,
  AVG(platelet)                     AS platelet_mean,
  AVG(potassium)                    AS potassium_mean,
  AVG(ptt)                          AS ptt_mean,
  AVG(inr)                          AS inr_mean,
  AVG(sodium)                       AS sodium_mean,
  AVG(bun)                          AS bun_mean,
  AVG(wbc)                          AS wbc_mean,
  MIN(bg_baseexcess)                AS baseexcess_min,
  MIN(bg_carboxyhemoglobin)         AS carboxyhemoglobin_min,
  MIN(bg_methemoglobin)             AS methemoglobin_min,
  MIN(bg_po2)                       AS po2_min,
  MIN(bg_pco2)                      AS pco2_min,
  MIN(bg_ph)                        AS ph_min,
  MIN(bg_pao2fio2ratio)             AS pao2fio2ratio_min,
  MIN(bg_totalco2)                  AS totalco2_min,
  MIN(aniongap)                     AS aniongap_min,
  MIN(albumin)                      AS albumin_min,
  MIN(bands)                        AS bands_min,
  MIN(bicarbonate)                  AS bicarbonate_min,
  MIN(bilirubin)                    AS bilirubin_min,
  MIN(calcium)                      AS calcium_min,
  MIN(creatinine)                   AS creatinine_min,
  MIN(chloride)                     AS chloride_min,
  MIN(hematocrit)                   AS hematocrit_min,
  MIN(hemoglobin)                   AS hemoglobin_min,
  MIN(lactate)                      AS lactate_min,
  MIN(platelet)                     AS platelet_min,
  MIN(potassium)                    AS potassium_min,
  MIN(ptt)                          AS ptt_min,
  MIN(inr)                          AS inr_min,
  MIN(sodium)                       AS sodium_min,
  MIN(bun)                          AS bun_min,
  MIN(wbc)                          AS wbc_min,
  MAX(bg_baseexcess)                AS baseexcess_max,
  MAX(bg_carboxyhemoglobin)         AS carboxyhemoglobin_max,
  MAX(bg_methemoglobin)             AS methemoglobin_max,
  MAX(bg_po2)                       AS po2_max,
  MAX(bg_pco2)                      AS pco2_max,
  MAX(bg_ph)                        AS ph_max,
  MAX(bg_pao2fio2ratio)             AS pao2fio2ratio_max,
  MAX(bg_totalco2)                  AS totalco2_max,
  MAX(aniongap)                     AS aniongap_max,
  MAX(albumin)                      AS albumin_max,
  MAX(bands)                        AS bands_max,
  MAX(bicarbonate)                  AS bicarbonate_max,
  MAX(bilirubin)                    AS bilirubin_max,
  MAX(calcium)                      AS calcium_max,
  MAX(creatinine)                   AS creatinine_max,
  MAX(chloride)                     AS chloride_max,
  MAX(hematocrit)                   AS hematocrit_max,
  MAX(hemoglobin)                   AS hemoglobin_max,
  MAX(lactate)                      AS lactate_max,
  MAX(platelet)                     AS platelet_max,
  MAX(potassium)                    AS potassium_max,
  MAX(ptt)                          AS ptt_max,
  MAX(inr)                          AS inr_max,
  MAX(sodium)                       AS sodium_max,
  MAX(bun)                          AS bun_max,
  MAX(wbc)                          AS wbc_max,
  -- total urine output
  SUM(urineoutput)                  AS urineoutput
FROM mp_data d
JOIN mp_cohort c USING (icustay_id)
WHERE hr BETWEEN 0 AND 12
GROUP BY d.subject_id, d.hadm_id, d.icustay_id
ORDER BY d.subject_id, d.hadm_id, d.icustay_id;

select * from mp_data_12hr;