--In psql prompt (psql -h localhost -U you -d mimiciii)
DROP TABLE IF EXISTS icustays;
CREATE TABLE icustays (
  ROW_ID    INT,
  SUBJECT_ID INT,
  HADM_ID   INT,
  ICUSTAY_ID INT,
  DBSOURCE  TEXT,
  FIRST_CAREUNIT TEXT,
  LAST_CAREUNIT  TEXT,
  FIRST_WARDID   INT,
  LAST_WARDID    INT,
  INTIME    TIMESTAMP,
  OUTTIME   TIMESTAMP,
  LOS       DOUBLE PRECISION
);



DROP TABLE IF EXISTS admissions;
CREATE TABLE admissions (
	ROW_ID INT,
	SUBJECT_ID INT,
	HADM_ID INT,
	ADMITTIME TIMESTAMP,
	DISCHTIME TIMESTAMP,
	DEATHTIME TIMESTAMP,
	ADMISSION_TYPE TEXT,
	ADMISSION_LOCATION TEXT,
	DISCHARGE_LOCATION TEXT,
	INSURANCE TEXT,
	LANGUAGE TEXT,
	RELIGION TEXT,
	MARITAL_STATUS TEXT,
	ETHNICITY TEXT,
	EDREGTIME TIMESTAMP,
	EDOUTTIME TIMESTAMP,
	DIAGNOSIS TEXT,
	HOSPITAL_EXPIRE_FLAG INT,
	HAS_CHARTEVENTS_DATA INT
	);

DROP TABLE IF EXISTS patients;
CREATE TABLE patients (
	ROW_ID INT,
	SUBJECT_ID INT,
	GENDER TEXT,
	DOB TIMESTAMP,
	DOD TIMESTAMP,
	DOD_HOSP TIMESTAMP,
	DOD_SSN TIMESTAMP,
	EXPIRE_FLAG INT
	);

DROP TABLE IF EXISTS chartevents_staging;
CREATE TABLE chartevents_staging (
  ROW_ID      TEXT,
  SUBJECT_ID  TEXT,
  HADM_ID     TEXT,
  ICUSTAY_ID  TEXT,
  ITEMID      TEXT,
  CHARTTIME   TEXT,
  STORETIME   TEXT,
  CGID        TEXT,
  VALUE       TEXT,
  VALUENUM    TEXT,
  VALUEUOM    TEXT,
  WARNING     TEXT,
  ERROR       TEXT,
  RESULTSTATUS TEXT,
  STOPPED     TEXT
);


DROP TABLE IF EXISTS chartevents;
CREATE TABLE chartevents (
	ROW_ID INT,
	SUBJECT_ID INT,
	HADM_ID INT,
	ICUSTAY_ID INT,
	ITEMID INT,
	CHARTTIME TIMESTAMP,
	STORETIME TIMESTAMP,
	CGID INT,
	VALUE DOUBLE PRECISION,
	VALUENUM DOUBLE PRECISION,
	VALUEUOM TEXT,
	WARNING INT,
	ERROR INT,
	RESULTSTATUS DOUBLE PRECISION,
	STOPPED DOUBLE PRECISION
	);

DROP TABLE IF EXISTS labevents;
CREATE TABLE labevents (
	ROW_ID INT,
	SUBJECT_ID INT,
	HADM_ID DOUBLE PRECISION,
	ITEMID INT,
	CHARTTIME TIMESTAMP,
	VALUE TEXT,
	VALUENUM DOUBLE PRECISION,
	VALUEUOM TEXT,
	FLAG TEXT
	);

DROP TABLE IF EXISTS outputevents;
CREATE TABLE outputevents (
	ROW_ID INT,
	SUBJECT_ID INT,
	HADM_ID INT,
	ICUSTAY_ID INT,
	CHARTTIME TIMESTAMP,
	ITEMID INT,
	VALUE INT,
	VALUEUOM TEXT,
	STORETIME TIMESTAMP,
	CGID INT,
	STOPPED DOUBLE PRECISION,
	NEWBOTTLE DOUBLE PRECISION,
	ISERROR DOUBLE PRECISION
	);

DROP TABLE IF EXISTS mp_hourly_cohort;
CREATE TABLE mp_hourly_cohort (
	SUBJECT_ID INT,
	HADM_ID INT,
	ICUSTAY_ID INT,
	HR INT
	);

DROP TABLE IF EXISTS mp_gcs;
CREATE TABLE mp_gcs (
	ICUSTAY_ID INT,
	HR INT,
	GCS INT,
	GCSMOTOR DOUBLE PRECISION,
	GCSVERBAL DOUBLE PRECISION,
	GCSEYES DOUBLE PRECISION,
	ENDOTRACHFLAG INT
	);

DROP TABLE IF EXISTS mp_lab;
CREATE TABLE mp_lab (
	HADM_ID INT,
	HR INT,
	ANIONGAP DOUBLE PRECISION,
	ALBUMIN DOUBLE PRECISION,
	BANDS DOUBLE PRECISION,
	BICARBONATE DOUBLE PRECISION,
	BILIRUBIN DOUBLE PRECISION,
	CREATININE DOUBLE PRECISION,
	CHLORIDE DOUBLE PRECISION,
	GLUCOSE DOUBLE PRECISION,
	HEMATOCRIT DOUBLE PRECISION,
	HEMOGLOBIN DOUBLE PRECISION,
	LACTATE DOUBLE PRECISION,
	PLATELET DOUBLE PRECISION,
	POTASSIUM DOUBLE PRECISION,
	PTT DOUBLE PRECISION,
	INR DOUBLE PRECISION,
	PT DOUBLE PRECISION,
	SODIUM DOUBLE PRECISION,
	BUN DOUBLE PRECISION,
	WBC DOUBLE PRECISION
	);